I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 424, in script
    scene computer office AI
Exception: Image 'computer office' does not accept attributes 'AI'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 424, in script
    scene computer office AI
  File "C:\Users\admin\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1542, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\admin\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "C:\Users\admin\Downloads\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\admin\Downloads\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\admin\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "C:\Users\admin\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'computer office' does not accept attributes 'AI'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
SaveGameIndustry 1.0
Mon Dec  5 17:01:35 2022
